### ISSUE TITLE
Fix location of rendered tutorial

### ISSUE THREAD

**Issue by hlapp** [bioruby/documents#4]
The [Tutorial wiki page](https://github.com/bioruby/documents/wiki/Tutorial) links to a rendered version on an unofficial site, which apparently has since disappeared. The correct link should be this: http://bioruby.org/doc/Tutorial.rd.html

The Edit function is disabled for non-committers, and so I can't change it myself.

**Comment by ngoto** [comment]
Thanks. Fixed by 96af5d4183dec3bd25c159538fac19c58fb53624
